import { WordCategory } from './types';

export const BUILTIN_CATEGORIES: WordCategory[] = [
  {
    id: 'animals',
    name: 'Animals',
    description: 'Learn names of common and cute animals',
    icon: 'dog',
    words: [
      { word: 'Cat', translation: 'Feline helper' },
      { word: 'Dog', translation: 'Barking friend' },
      { word: 'Rabbit', translation: 'Long-eared hopper' },
      { word: 'Lion', translation: 'King of the jungle' },
      { word: 'Panda', translation: 'Bamboo eater' },
      { word: 'Monkey', translation: 'Climbing acrobat' },
      { word: 'Tiger', translation: 'Striped hunter' },
      { word: 'Horse', translation: 'Fast runner' },
      { word: 'Bear', translation: 'Forest giant' },
      { word: 'Elephant', translation: 'Trunk nose' },
      { word: 'Fox', translation: 'Clever friend' },
      { word: 'Frog', translation: 'Green hopper' },
      { word: 'Giraffe', translation: 'Long neck' },
      { word: 'Zebra', translation: 'Striped horse' },
      { word: 'Penguin', translation: 'Ice bird' },
      { word: 'Koala', translation: 'Eucalyptus climber' },
      { word: 'Kangaroo', translation: 'Pouch jumper' },
      { word: 'Dolphin', translation: 'Ocean swimmer' },
      { word: 'Whale', translation: 'Huge sea friend' },
      { word: 'Wolf', translation: 'Forest hunter' },
      { word: 'Owl', translation: 'Wise night bird' },
      { word: 'Cow', translation: 'Milk helper' },
      { word: 'Sheep', translation: 'Wool friend' },
      { word: 'Deer', translation: 'Horned friend' },
      { word: 'Squirrel', translation: 'Nut collector' },
      { word: 'Hedgehog', translation: 'Spiky friend' },
      { word: 'Mouse', translation: 'Tiny helper' },
      { word: 'Pig', translation: 'Pink snout' },
      { word: 'Duck', translation: 'Water waddler' },
      { word: 'Goat', translation: 'Horned helper' },
    ],
  },
  {
    id: 'fruits',
    name: 'Fruits',
    description: 'Juicy and delicious sweet treats',
    icon: 'apple',
    words: [
      { word: 'Apple', translation: 'Crisp fruit' },
      { word: 'Banana', translation: 'Yellow sweet strip' },
      { word: 'Lemon', translation: 'Sour yellow' },
      { word: 'Peach', translation: 'Soft pink sweet' },
      { word: 'Cherry', translation: 'Red twins' },
      { word: 'Orange', translation: 'Juicy dynamic color' },
      { word: 'Melon', translation: 'Big sweet fruit' },
      { word: 'Grape', translation: 'Vine clusters' },
      { word: 'Pear', translation: 'Sweet teardrop' },
      { word: 'Plum', translation: 'Purple sweet' },
      { word: 'Mango', translation: 'Golden tropical' },
      { word: 'Kiwi', translation: 'Fuzzy green slice' },
      { word: 'Strawberry', translation: 'Sweet red heart' },
      { word: 'Pineapple', translation: 'Crown tropical' },
      { word: 'Watermelon', translation: 'Giant striped sweet' },
      { word: 'Apricot', translation: 'Small peach' },
      { word: 'Blueberry', translation: 'Tiny blue ball' },
      { word: 'Raspberry', translation: 'Pink forest cluster' },
      { word: 'Coconut', translation: 'Hard brown nut' },
      { word: 'Grapefruit', translation: 'Big bitter orange' },
      { word: 'Blackberry', translation: 'Dark sweet cluster' },
      { word: 'Fig', translation: 'Soft purple sweet' },
      { word: 'Lime', translation: 'Sour green' },
      { word: 'Papaya', translation: 'Orange tropical slice' },
      { word: 'Pomegranate', translation: 'Red seed chest' },
      { word: 'Avocado', translation: 'Green cream pear' },
      { word: 'Cranberry', translation: 'Sour red marsh' },
      { word: 'Tangerine', translation: 'Small sweet orange' },
      { word: 'Olive', translation: 'Tiny green oil' },
      { word: 'Persimmon', translation: 'Sweet orange winter' },
    ],
  },
  {
    id: 'colors',
    name: 'Colors',
    description: 'Beautiful visible light spectrum hues',
    icon: 'palette',
    words: [
      { word: 'Red', translation: 'Fire glow hue' },
      { word: 'Blue', translation: 'Clear sky shade' },
      { word: 'Green', translation: 'Spring grass tone' },
      { word: 'Yellow', translation: 'Bright sun paint' },
      { word: 'Pink', translation: 'Soft rose glow' },
      { word: 'Purple', translation: 'Royal berry hue' },
      { word: 'White', translation: 'Pure snow shade' },
      { word: 'Black', translation: 'Midnight dark look' },
      { word: 'Brown', translation: 'Warm wood tone' },
      { word: 'Gray', translation: 'Rain cloud color' },
      { word: 'Orange', translation: 'Sunset glow light' },
      { word: 'Golden', translation: 'Vibrant metallics' },
      { word: 'Silver', translation: 'Polished white metal' },
      { word: 'Beige', translation: 'Soft sand tone' },
      { word: 'Lime', translation: 'Fierce green light' },
      { word: 'Violet', translation: 'Soft purple mist' },
      { word: 'Indigo', translation: 'Deep night blue' },
      { word: 'Turquoise', translation: 'Sea green shade' },
      { word: 'Cyan', translation: 'Electric sky tint' },
      { word: 'Magenta', translation: 'Deep power pink' },
      { word: 'Crimson', translation: 'Rich dark red' },
      { word: 'Lavender', translation: 'Purple flower shade' },
      { word: 'Amber', translation: 'Golden gem glow' },
      { word: 'Maroon', translation: 'Chestnut dark red' },
      { word: 'Navy', translation: 'Deep sea uniform' },
      { word: 'Olive', translation: 'Dark green branch' },
      { word: 'Emerald', translation: 'Green jewel gleam' },
      { word: 'Coral', translation: 'Warm ocean pink' },
      { word: 'Peach', translation: 'Soft orange-cream' },
      { word: 'Bronze', translation: 'Aged brown metal' },
    ],
  },
  {
    id: 'numbers',
    name: 'Numbers',
    description: 'Count items and quantify values',
    icon: 'hash',
    words: [
      { word: 'One', translation: 'Count 1' },
      { word: 'Two', translation: 'Count 2' },
      { word: 'Three', translation: 'Count 3' },
      { word: 'Four', translation: 'Count 4' },
      { word: 'Five', translation: 'Count 5' },
      { word: 'Six', translation: 'Count 6' },
      { word: 'Seven', translation: 'Count 7' },
      { word: 'Eight', translation: 'Count 8' },
      { word: 'Nine', translation: 'Count 9' },
      { word: 'Ten', translation: 'Count 10' },
      { word: 'Zero', translation: 'Empty value' },
      { word: 'Eleven', translation: 'Count 11' },
      { word: 'Twelve', translation: 'Count 12' },
      { word: 'Twenty', translation: 'Count 20' },
      { word: 'Hundred', translation: 'Count 100' },
      { word: 'Thousand', translation: 'Count 1000' },
      { word: 'Thirteen', translation: 'Count 13' },
      { word: 'Fourteen', translation: 'Count 14' },
      { word: 'Fifteen', translation: 'Count 15' },
      { word: 'Sixteen', translation: 'Count 16' },
      { word: 'Seventeen', translation: 'Count 17' },
      { word: 'Eighteen', translation: 'Count 18' },
      { word: 'Nineteen', translation: 'Count 19' },
      { word: 'Thirty', translation: 'Count 30' },
      { word: 'Forty', translation: 'Count 40' },
      { word: 'Fifty', translation: 'Count 50' },
      { word: 'Sixty', translation: 'Count 60' },
      { word: 'Seventy', translation: 'Count 70' },
      { word: 'Eighty', translation: 'Count 80' },
      { word: 'Ninety', translation: 'Count 90' },
    ],
  },
  {
    id: 'shapes',
    name: 'Shapes',
    description: 'Geometric structures and figures',
    icon: 'heart',
    words: [
      { word: 'Star', translation: 'Night sky light shape' },
      { word: 'Heart', translation: 'Love symbol shape' },
      { word: 'Circle', translation: 'Round ring shape' },
      { word: 'Square', translation: 'Four equal sides shape' },
      { word: 'Triangle', translation: 'Three corners shape' },
      { word: 'Diamond', translation: 'Sparkling gem shape' },
      { word: 'Rectangle', translation: 'Long box shape' },
      { word: 'Oval', translation: 'Egg line shape' },
      { word: 'Hexagon', translation: 'Six corners shape' },
      { word: 'Pentagon', translation: 'Five corners shape' },
      { word: 'Octagon', translation: 'Eight corners shape' },
      { word: 'Cylinder', translation: 'Can roll shape' },
      { word: 'Cone', translation: 'Party hat shape' },
      { word: 'Sphere', translation: 'Ball round shape' },
      { word: 'Cube', translation: 'Block box shape' },
      { word: 'Pyramid', translation: 'Egypt stone shape' },
      { word: 'Cross', translation: 'Plus sign shape' },
      { word: 'Crescent', translation: 'New moon shape' },
      { word: 'Arrow', translation: 'Pointer sign shape' },
      { word: 'Line', translation: 'Straight track shape' },
      { word: 'Point', translation: 'Dot sign shape' },
      { word: 'Ring', translation: 'Loop finger shape' },
      { word: 'Box', translation: 'Container square shape' },
      { word: 'Spiral', translation: 'Coil curl shape' },
      { word: 'Wave', translation: 'Ripple curves shape' },
      { word: 'Curve', translation: 'Bent line shape' },
      { word: 'Wedge', translation: 'Incline slide shape' },
      { word: 'Arc', translation: 'Rainbow bow shape' },
      { word: 'Corner', translation: 'Turn edge shape' },
      { word: 'Tube', translation: 'Hollow pipe shape' },
    ],
  },
  {
    id: 'nature',
    name: 'Nature',
    description: 'Objects representing our planet and biosphere',
    icon: 'tree',
    words: [
      { word: 'Sun', translation: 'Bright yellow day star' },
      { word: 'Moon', translation: 'White glowing night light' },
      { word: 'Rain', translation: 'Falling water clouds' },
      { word: 'Wind', translation: 'Blowing airy breeze' },
      { word: 'Snow', translation: 'Cold white ice flakes' },
      { word: 'Tree', translation: 'Tall woody green plant' },
      { word: 'Flower', translation: 'Sweet smelling bloom' },
      { word: 'River', translation: 'Flowing water path' },
      { word: 'Cloud', translation: 'Fluffy white air pillow' },
      { word: 'Sky', translation: 'Deep blue atmosphere' },
      { word: 'Forest', translation: 'Lush green dense woods' },
      { word: 'Lake', translation: 'Quiet standing water pond' },
      { word: 'Leaf', translation: 'Flat green tree helper' },
      { word: 'Grass', translation: 'Green carpet soil lining' },
      { word: 'Rainbow', translation: 'Seven color dynamic bow' },
      { word: 'Mountain', translation: 'Giant sloped rock height' },
      { word: 'Ocean', translation: 'Huge world water body' },
      { word: 'Sea', translation: 'Salty coastline water' },
      { word: 'Stone', translation: 'Small hard ground piece' },
      { word: 'Rock', translation: 'Big solid ancient mass' },
      { word: 'Sand', translation: 'Tiny golden shore grains' },
      { word: 'Fire', translation: 'Hot glowing yellow flame' },
      { word: 'Wave', translation: 'Curving ocean water wall' },
      { word: 'Beach', translation: 'Sunny sandy sea edge' },
      { word: 'Hill', translation: 'Gentle grassy green slope' },
      { word: 'Field', translation: 'Flat open grass meadow' },
      { word: 'Storm', translation: 'Loud rainy wind dark' },
      { word: 'Ice', translation: 'Frozen solid cool water' },
      { word: 'Bud', translation: 'Unopened baby flower' },
      { word: 'Bush', translation: 'Dense short leafy plant' },
    ],
  },
];
